### ISSUE TITLE
Assertion failed: (f->e != 0)

### ISSUE THREAD

**Issue by karel-brinda** [lh3/ropebwt3#1]
FIrst of all, big congrats for all this work!

I've made a little experiment with 600 bact genomes (`./ropebwt3 build -t10 -bo bwt.fmr`), which seemed to be constructed correctly.

However, when I run the stat command, I get:
```
$ ./ropebwt3 stat bwt.fmr
[M::mr_restore] ($, A, C, G, T, N) = (1490118, 791852006, 519124575, 519124575, 791852006, 160)
1490118 sequences
2623443440 symbols
Assertion failed: (f->e != 0), function rb3_fmi_get_r, file fm-index.c, line 573.
Abort trap: 6
```

System: OS X
Version: b033029

**Comment by lh3** [comment]
Due to my laziness, `stat` only works for the [FMD encoding](https://github.com/lh3/ropebwt3?tab=readme-ov-file#format) at the moment. You will need to convert FMR to FMD and then apply `stat`:
```sh
ropebwt3 build -i bwt.fmr -do bwt.fmd   # convert FMR to FMD
ropebwt3 stat bwt.fmd
```
I will keep this issue open until I implement `stat` for the FMR encoding as well.
