### ISSUE TITLE
Maximum 25 haplotype for hapdiv

### ISSUE THREAD

**Issue by baozg** [lh3/ropebwt3#2]
Hi, @lh3 

Thanks for bring this amazing tools for full-text pangenome search! I tried to build index with 271 A.thaliana long reads genome, it only takes 6 hours to merge all index!

But I found that the maximum distinct haps from `ropebwt3 hapdiv` only report to 25, is that excepted?

Version: `b033029`
OS: Ubuntun 20

```shell
parallel -j 12 'ropebwt3 build -t 4 -bo {}.fmr fasta/{}.Chr_scaffolds.fa' ::: `cat unique.list`
ropebwt3 merge -t 32 -o Ath271_unique.fmr Col-CC.fmr 1*.fmr
ropebwt3 hapdiv -t 32 Ath271_unique.fmr query.fasta > Ath271_unique.hapdiv
```

**Comment by shenwei356** [comment]
This option might help:

```
  -N INT      keep up to INT hits per DAWG node [25]
```

**Comment by baozg** [comment]
My bad. Thanks you for reminding! @shenwei356

**Comment by attractivechaos** [comment]
Thank you, @shenwei356.

Two minor things. The static [FMD format](https://github.com/lh3/ropebwt3?tab=readme-ov-file#format) is usually faster for sequence search than the dynamic FMR format. I have just added [more instructions](https://github.com/lh3/ropebwt3?tab=readme-ov-file#build) on how to generate sampled suffix array and the sequence name file. The `sw` command uses sampled suffix array to output coordinates and the sequence name file to output contig names in the PAF format.
