### ISSUE TITLE
handling of identifiers in small sequences

### ISSUE THREAD

**Issue by rchikhi** [lh3/ropebwt3#3]
Hi Heng,

great tool!

The behavior of `sw` on small sequences has a small bug when reporting reference coordinates, I believe. Consider this test file:

```
$ cat test.fa
>seqA1
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
>seqB2
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
```

Prepared with:

```
seqtk comp test.fa | cut -f1,2  | gzip > test.fmd.len.gz
./ropebwt3 build -do test.fmd -r test.fmr test.fa
./ropebwt3 ssa test.fmd -o test.fmd.ssa
```

Aligning the first sequence, returns the name of the second:

```
 echo AAAAAAAAAAAAAAAAAAA | ./ropebwt3 sw -Lm10  test.fmd -
[M::rb3_fmi_load_all::0.000*6.10] loaded the BWT
[M::rb3_fmi_load_all::0.001*2.73] loaded the sampled suffix array
[M::rb3_fmi_load_all::0.001*1.86] loaded the sequence names and lengths
seq1    19      0       19      -       seqB2   49      0       19      19      19      0       AS:i:19 qh:i:1  rh:i:31 cg:Z:19=        cs:Z::19
```

Yet, passing `-s1` to the `ssa` command  (SA sampling to every 2 bases) doesn't change anything.

Stranger, aligning the revcomp of the second sequences returns the name of the first reference :)

```
echo GGGGGGGGGGGGG | ./ropebwt3 sw -Lm10  test.fmd -
[M::rb3_fmi_load_all::0.000*7.35] loaded the BWT
[M::rb3_fmi_load_all::0.001*2.92] loaded the sampled suffix array
[M::rb3_fmi_load_all::0.001*1.89] loaded the sequence names and lengths
seq1    13      0       13      -       seqA1   49      0       13      13      13      0       AS:i:13 qh:i:1  rh:i:37 cg:Z:13=        cs:Z::13
```

best,
Rayan

**Comment by lh3** [comment]
Option `-r` changes the sequence order. You have seqA1-, seqB2+, seqB2- and seqA1+ in the index, not the expected seqA1+, seqA1-, seqB2+ and seqB2-.

Ideally, there should be a way to check the consistency between `.len.gz` and `.fmd`, or generating `.len.gz` while indexing.

**Comment by rchikhi** [comment]
ohhh, `-r` in `build` was indeed the culprit! Thanks, no issues anymore.
